name = "fitzoneapparels"
main = ".open-next/worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ADMIN_EMAIL = "amrit@fitzoneapparels.com"
ADMIN_PASSWORD = "fitzoneadmin123"
JWT_SECRET = "super-secret-key"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "fittzone"
database_id = "aa65feef-9e5d-4bc2-8a92-1306ea51111e"

# R2 Bucket binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "fitzone-bucket"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
